agent_name = "gemini-screen-ui-kit"
image = "your_username/gemini-screen-ui-kit:0.1"
image_credentials = "your_dockerhub_pull_secret"
secret_set = "gemini-screen-ui-kit-secrets"
agent_profile = "agent-2x"

[krisp_viva]
	audio_filter = "tel"

[scaling]
	min_agents = 1
