[project]
name = "gemini-screen-ui-kit"
version = "0.1.0"
description = "Pipecat Example showcasing Gemini Live with screen share capabilities"
requires-python = ">=3.10"
dependencies = [
    "pipecat-ai[webrtc,daily,silero,google,runner]>=0.0.102",
    "pipecatcloud>=0.2.18"
]

[dependency-groups]
dev = [
    "ruff~=0.12.1",
]

[tool.ruff]
line-length = 100
[tool.ruff.lint]
select = ["I"]