agent_name = "daily-twilio-sip-dial-in"
image = "hushdaily/daily-twilio-sip-dial-in:0.2"
image_credentials = "my-image-pull-secret"
secret_set = "daily-twilio-sip-secrets"
agent_profile = "agent-1x"

[scaling]
	min_agents = 1
