agent_name = "daily-twilio-sip-dial-in-eu"
image = "hushdaily/daily-twilio-sip-dial-in-eu:0.3"
image_credentials = "docker-creds"
secret_set = "daily-twilio-sip-secrets-eu"
agent_profile = "agent-1x"
region = "eu-central"

[scaling]
	min_agents = 1
