[project]
name = "studypal"
version = "0.1.0"
description = "Studypal example"
requires-python = ">=3.10"
dependencies = [
    "aiohttp",
    "pipecat-ai[daily,anthropic,cartesia,silero]>=0.0.99",
]

[dependency-groups]
dev = [
    "pyright>=1.1.404,<2",
    "ruff>=0.12.11,<1",
]

[tool.ruff]
line-length = 100
[tool.ruff.lint]
select = ["I"]
