[project]
name = "twilio-chatbot-dial-in"
version = "0.1.0"
description = "Twilio dial-in example for Pipecat"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pipecat-ai[websocket,cartesia,google,silero,deepgram,runner]>=0.0.99",
    "pipecatcloud>=0.2.7",
]

[dependency-groups]
dev = [
    "pyright>=1.1.404,<2",
    "ruff>=0.12.11,<1",
]

[tool.ruff]
line-length = 100
[tool.ruff.lint]
select = ["I"]
