[project]
name = "inbound"
version = "0.1.0"
description = "Twilio inbound chatbot"
requires-python = ">=3.10"
dependencies = [
    "aiofiles",
    "aiohttp",
    "pipecat-ai[websocket,cartesia,openai,silero,deepgram,runner]==0.0.99",
]

[dependency-groups]
dev = [
    "pyright>=1.1.404,<2",
    "ruff>=0.12.11,<1",
]

[tool.ruff]
line-length = 100
[tool.ruff.lint]
select = ["I"]
