[project]
name = "push-to-talk"
version = "0.1.0"
description = "Push to talk example"
requires-python = ">=3.10"
dependencies = [
    "pipecat-ai[daily,webrtc,deepgram,openai,silero,cartesia,runner]>=0.0.102",
    "pipecatcloud>=0.2.20",
]

[dependency-groups]
dev = [
    "ruff~=0.12.1",
    "pyright>=1.1.404,<1.2",
]

[tool.ruff]
line-length = 100
[tool.ruff.lint]
select = ["I"]
