[project]
name = "aws-agentcore-websocket-server"
version = "0.1.0"
description = "Server for AWS AgentCore WebSocket example"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.6",
    "uvicorn>=0.34.0",
    "python-dotenv>=1.0.1",
    "boto3>=1.35.85",
]
