[project]
name = "pipecat-jaeger-tracing"
version = "0.1.0"
description = "A Pipecat example using Jaeger tracing"
requires-python = ">=3.10"
dependencies = [
    "pipecat-ai[daily,webrtc,websocket,silero,cartesia,deepgram,openai,tracing,runner]>=0.0.102",
    "pipecatcloud>=0.2.20",
    "opentelemetry-exporter-otlp-proto-grpc",
]

[dependency-groups]
dev = [
    "ruff~=0.12.1",
]

[tool.ruff]
line-length = 100
[tool.ruff.lint]
select = ["I"]