agent_name = "daily-twilio-sip-dial-out"
image = "your_username/daily-twilio-sip-dial-out:0.1"
image_credentials = "your_dockerhub_image_pull_secret"
secret_set = "daily-twilio-sip-secrets"

[scaling]
	min_agents = 1
