agent_name = "pcc-gemini-twilio"
image = "your_username/pcc-gemini-twilio:0.1"
image_credentials = "your_dockerhub_pull_secret"
secret_set = "pcc-gemini-twilio-secrets"
enable_krisp = true
agent_profile = "agent-1x"

[scaling]
	min_agents = 1
