[project]
name = "server"
version = "0.1.0"
description = "Pipecat example - server"
requires-python = ">=3.10"
dependencies = [
    "pipecat-ai[daily,openai,elevenlabs,google,silero]>=0.0.102",
    "python-dotenv==1.0.1",
    "modal==1.0.5",
    "fastapi[all]",
]

[dependency-groups]
dev = [
    "pyright>=1.1.404,<2",
    "ruff>=0.12.11,<1",
]

[tool.ruff]
line-length = 100
[tool.ruff.lint]
select = ["I"]
