agent_name = "simple-chatbot"
image = "your_dockerhub_username/simple-chatbot:0.1"
secret_set = "simple-chatbot-secrets"
agent_profile = "agent-1x"

# RECOMMENDED: Set an image pull secret:
# https://docs.pipecat.ai/deployment/pipecat-cloud/fundamentals/secrets#image-pull-secrets
# image_credentials = "your_dockerhub_image_pull_secret"

[scaling]
	min_agents = 1