[project]
name = "plivo-chatbot-dial-out"
version = "0.1.0"
description = "Plivo dial-out example for Pipecat"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "pipecat-ai[websocket,cartesia,openai,silero,deepgram,runner,local-smart-turn-v3]>=0.0.99",
  "pipecatcloud>=0.2.4"
]
