[project]
name = "server"
version = "0.1.0"
description = "Pipecat example - server"
requires-python = ">=3.10"
dependencies = [
    "async_timeout,
    "fastapi,
    "uvicorn,
    "python-dotenv,
    "pipecat-ai[daily,silero,openai,cartesia,google]==0.0.99,,
]

[dependency-groups]
dev = [
    "pyright>=1.1.404,<2,
    "ruff>=0.12.11,<1,
]

[tool.ruff]
line-length = 100
[tool.ruff.lint]
select = ["I"]
