agent_name = "translation-chatbot"
image = "your_username/translation-chatbot:0.1"
image_credentials = "your_dockerhub_image_pull_secret"
secret_set = "translation-chatbot"

[scaling]
	min_agents = 1
