[project]
name = "telnyx-chatbot-dial-in"
version = "0.1.0"
description = "Telnyx dial-in example for Pipecat"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "pipecat-ai[websocket,cartesia,openai,silero,deepgram,runner,webrtc]>=0.0.99",
  "pipecatcloud>=0.2.7"
]
