agent_name = "1000-concurrent-agents"
image = "your_username/1000-concurrent-agents:0.1"
image_credentials = "your_dockerhub_image_pull_secret"
secret_set = "concurrent-agents-secrets"
agent_profile = "agent-1x"

[scaling]
	min_agents = 1
