agent_name = "1000-concurrent-agents"
image = "hushdaily/1000-concurrent-agents:0.2"
image_credentials = "my-image-pull-secret"
secret_set = "1000-concurrent-agents-secrets"
agent_profile = "agent-1x"

[scaling]
	min_agents = 50
    max_agents = 50
